apiVersion: v1
kind: Service
metadata:
  name: tenant
spec:
  type: LoadBalancer
  selector:
    app: tenant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 192.168.0.122