apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-dependencies
  namespace: linkerd
configurations:
  - kustomizeconfig.yaml
resources:
  - rbac.yaml
  - sealed-secret.yaml
  - linkerd-certs.yaml
  - linkerd-crds.yaml
  - repositories.yaml
  - namespaces.yaml

