---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-dev-can-patch-linkerd
  namespace: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: can-patch
subjects:
- kind: Group
  name: 22a33fa7-4217-43c2-b97e-080b5acc548e
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-dev-can-patch-linkerd-viz
  namespace: linkerd-viz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: can-patch
subjects:
- kind: Group
  name: 22a33fa7-4217-43c2-b97e-080b5acc548e