apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqVENDQVRPZ0F3SUJBZ0lRR21kYkIxUU05dnc0c1V2b2tSYlFTekFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QTJNamN5TXpJMApNRFZhRncwek16QTJNalF5TXpJME1EVmFNQ1V4SXpBaEJnTlZCQU1UR25KdmIzUXViR2x1YTJWeVpDNWpiSFZ6CmRHVnlMbXh2WTJGc01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRW9NT0JURHFsK3BDdncxdFAKc3h5Mko1cEFEVFRCYXZkalNpSmpLTkUzTGM3Vlpia05FZUNvbm9sR2RjNmFDcktpOFNwU1pvRytzZW4xL1FGMwpFVmxxbXFORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRRXdIUVlEClZSME9CQllFRkdOY0pLeDMzZWpMbGlrc3BBSmRudWM2aUtXUE1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lGYXgKbzFYd2NLRHNDMXVYakREUnlPSXkxMldiTy9QdmZDRTVtSGExOXBVSUFpRUExSENtSHF3OXlzanovRGZtcVRUOQo1RkhsSk15SEhWL216ejhOTWVGS0IyYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtvT29sb1VPN054aG1FZVN3a3JHbUtYdUdWejJtMkU4NjVBbE8rM0tpaldvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFb01PQlREcWwrcEN2dzF0UHN4eTJKNXBBRFRUQmF2ZGpTaUpqS05FM0xjN1ZaYmtORWVDbwpub2xHZGM2YUNyS2k4U3BTWm9HK3NlbjEvUUYzRVZscW1nPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: linkerd-trust-anchor
  namespace: linkerd
type: kubernetes.io/tls
