---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: hello-nginx
  namespace: flux-system
spec:
  image: novasdream/hello-nginx
  interval: 1m0s
---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: hello-nginx
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-nginx