apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: security
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/security
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: security
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: security
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: tenant
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/tenant
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: tenant
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: tenant
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: document
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/document
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: document
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: document
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: loan 
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/loan
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: loan
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: loan
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: party
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/party
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: party
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: party
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: onboarding
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/onboarding
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: onboarding
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: onboarding
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: matching 
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/matching
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: matching
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: matching
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: communication
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/communication
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: communication
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: communication
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: message
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/message
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: message
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: message
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: example-dotnet
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/example-dotnet
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: example-dotnet
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: example-dotnet
