apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - image_update.yaml
  - ../azure-workload-id
  - ../cert-manager
  - ../dashboard
  - ../jaeger
  - ../linkerd
  - ../linkerd-viz
  - ../mic
  - ../sources
