apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - hello-nginx.yaml
  - image_update.yaml
  - ../cert-manager
  - ../dashboard
  - ../jaeger
  - ../linkerd
  - ../linkerd-viz
  - ../sources
