apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m0s # detect drift and undo kubectl edits every 5 minutes
  wait: true
  timeout: 10m0s
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
  prune: true
  force: true
  # targetNamespace: fintag # set the namespace for all resources
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/development
