# apiVersion: networking.k8s.io/v1beta1 # for k8s < v1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faces-ingress
  namespace: faces
  annotations:
    linkerd.io/inject: enabled
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: face.faces.local.lab.2bot.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: faces-gui
            port:
              number: 80
      # - path: /smiley/
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: face 
      #       port:
      #         number: 80
      # - path: /face
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: face 
      #       port:
      #         number: 80
      # - path: /color
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: color 
      #       port:
      #         number: 80

