---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: example-dotnet
  namespace: flux-system
spec:
  image: fintagcore.azurecr.io/example-dotnet
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: example-dotnet
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: example-dotnet

