apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: basic-nginx
  name: nginx-basic
  namespace: nginx-basic
spec:
  replicas: 2
  minReadySeconds: 5 # how long it should wait until it creates the next pod.
  selector:
    matchLabels:
      app: basic-nginx
  template:
    metadata:
      labels:
        app: basic-nginx
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: novasdream/hello-nginx:1.1.3 # {"$imagepolicy": "flux-system:hello-nginx"}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
      nodeSelector:
        kubernetes.io/os: linux
