apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - cert-manager.crds.yaml
patchesJson6902:
- target:
    version: v1
    group: apps
    kind: Deployment
    name: image-reflector-controller
    namespace: flux-system
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --azure-autologin-for-acr
    - op: add 
      path: /spec/template/metadata/labels/aadpodidbinding
      value: acr-azure
# technically not being used - flux is still using AAD Pod Identity with the first patch
- target:
    version: v1
    kind: ServiceAccount
    name: image-reflector-controller
    namespace: flux-system
  patch: |-
    - op: add
      path: /metadata/annotations
      value: 
        azure.workload.identity/tenant-id: "4d4dcfda-d925-4d37-9c0c-4a207d37a4b1"

