apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "v1.9.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 60s
  install:
    remediation:
      retries: 3
  values:
    podLabels:
      aadpodidbinding: certman-label
