apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-jaeger 
  namespace: linkerd
spec:
  releaseName: linkerd-jaeger
  chart:
    spec:
      chart: linkerd-jaeger
      version: "2.11.4"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 60s
  install:
    remediation:
      retries: 3
  values: {}
