---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd
spec:
  interval: 10m0s
  releaseName: linkerd-viz
  chart:
    spec:
      chart: linkerd-viz
      version: "2.11.4"
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
