apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization 
resources: 
  - rbac.yaml
  - ../base
patches:
- target:
    version: v1beta1
    group: image.toolkit.fluxcd.io
    kind: ImageUpdateAutomation
    name: .*
  patch: |-
    - op: add
      path: /spec/update/path
      value: ./apps/staging
    - op: add
      path: /spec/git/checkout/ref/branch
      value: staging
- target:
    version: v2beta1
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: aad-pod-identity
    namespace: kube-system
  patch: |-
    - op: add
      path: /spec/values/azureIdentities/acrId/resourceID
      value: /subscriptions/c8372520-b65a-444f-b090-5db0325b0456/resourcegroups/staging/providers/Microsoft.ManagedIdentity/userAssignedIdentities/staging-k8s-id
    - op: add
      path: /spec/values/azureIdentities/acrId/clientID
      value: 1136d9ce-5e09-43be-b1cc-136ea9959573
    - op: add
      path: /spec/values/azureIdentities/certMan/resourceID
      value: /subscriptions/c8372520-b65a-444f-b090-5db0325b0456/resourcegroups/staging/providers/Microsoft.ManagedIdentity/userAssignedIdentities/staging-cert-manager-dns01
    - op: add
      path: /spec/values/azureIdentities/certMan/clientID
      value: 74783962-716b-453b-80ee-0b374f795fea
- target:
    version: v1
    group: networking.k8s.io
    kind: Ingress
    name: "web-ingress"
  patch: |-
    - op: add
      path: /spec/rules/0/host
      value: linkerd.staging.fintag-core.net            
    - op: add
      path: /spec/tls/0/hosts
      value: 
        - linkerd.staging.fintag-core.net            
- target:
    version: v1
    group: networking.k8s.io
    kind: Ingress
    name: "kubernetes-dashboard"
  patch: |-
    - op: add
      path: /spec/rules/0/host
      value: k8s.staging.fintag-core.net            
    - op: add
      path: /spec/tls/0/hosts
      value: 
        - k8s.staging.fintag-core.net            
