apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: faces
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./faces/staging
  prune: true
  wait: true
  timeout: 1m0s