apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m0s # detect drift and undo kubectl edits every minute
  wait: true
  timeout: 1m0s # I droped it to see errors fast. 
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging

