apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m0s # detect drift and undo kubectl edits every minute
  wait: true
  timeout: 10m0s
  retryInterval: 2m0s # retry every two minutes on apply or waiting failures
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging

